-- This query extracts weights for adult ICU patients on their first ICU day.
-- It does *not* use any information after the first ICU day, as weight is
-- sometimes used to monitor fluid balance.

-- ** Requires the echodata view, generated by etc/echo-data.sql

DROP MATERIALIZED VIEW IF EXISTS weightfirstday CASCADE;
CREATE MATERIALIZED VIEW weightfirstday as
with ce as
(
    SELECT
      c.stay_id
      -- we take the median value from roughly first day
      -- TODO: eliminate obvious outliers if there is a reasonable weight
      -- (e.g. weight of 180kg and 90kg would remove 180kg instead of taking the median)
      , percentile_cont(0.5) WITHIN GROUP (ORDER BY valuenum) as Weight_Admit
    FROM mimiciv_icu.chartevents c
    inner join mimiciv_icu.icustays ie
        on c.stay_id = ie.stay_id
        and c.charttime <= ie.intime + interval '1' day
        and c.charttime > ie.intime - interval '1' day -- some fuzziness for admit time
    WHERE c.valuenum IS NOT NULL
    AND c.itemid in (762,226512) -- Admit Wt
    AND c.valuenum != 0
    -- exclude rows marked as error
    AND c.warning IS DISTINCT FROM 1
    group by c.stay_id
)
, dwt as
(
    SELECT
      c.stay_id
      , percentile_cont(0.5) WITHIN GROUP (ORDER BY valuenum) as Weight_Daily
    FROM mimiciv_icu.chartevents c
    INNER JOIN mimiciv_icu.icustays ie
        on c.stay_id = ie.stay_id
        and c.charttime <= ie.intime + interval '1' day
        and c.charttime > ie.intime - interval '1' day -- some fuzziness for admit time
    WHERE c.valuenum IS NOT NULL
    AND c.itemid in (763,224639) -- Daily Weight
    AND c.valuenum != 0
    -- exclude rows marked as error
    AND c.warning IS DISTINCT FROM 1
    group by c.stay_id
)
-- we split in-hospital/out of hospital echoes as we would like to prioritize in-hospital data
-- , echo_hadm as
-- (
--     select
--         ie.icustay_id
--         , 0.453592*percentile_cont(0.5) WITHIN GROUP (ORDER BY weight) as Weight_EchoInHosp
--     from echodata ec
--     inner join mimiciii.icustays ie
--         on ec.hadm_id = ie.hadm_id
--         and ec.charttime < ie.intime + interval '1' day
--     where
--             ec.HADM_ID is not null
--         and ec.weight is not null
--     group by ie.icustay_id
-- )
-- , echo_nohadm as
-- (
--     select
--         ie.icustay_id
--         , 0.453592*percentile_cont(0.5) WITHIN GROUP (ORDER BY weight) as Weight_EchoPreHosp
--     from echodata ec
--     inner join mimiciii.icustays ie
--         on ie.subject_id = ec.subject_id
--         and ie.intime < ec.charttime + interval '1' month
--         and ie.intime > ec.charttime
--     where
--             ec.HADM_ID is null
--         and ec.weight is not null
--     group by ie.icustay_id
-- )
select
    ie.stay_id
    , round(cast(
    case
        when ce.stay_id is not null
            then ce.Weight_Admit
        when dwt.stay_id is not null
            then dwt.Weight_Daily
        --when eh.icustay_id is not null
        --    then eh.Weight_EchoInHosp
        --when enh.icustay_id is not null
        --    then enh.Weight_EchoPreHosp
        else null end
        as numeric), 2)
    as Weight

    -- components
    , ce.Weight_Admit
    , dwt.Weight_Daily
    --, eh.Weight_EchoInHosp
    --, enh.Weight_EchoPreHosp

from mimiciv_icu.icustays ie

-- filter to only adults
inner join mimiciv_hosp.patients pat
    on ie.subject_id = pat.subject_id
    --and ie.intime > pat.dob + interval '1' year

-- admission weight
left join ce
    on ie.stay_id = ce.stay_id

-- daily weights
left join dwt
    on ie.stay_id = dwt.stay_id

-- in-hospital echo weight
--left join echo_hadm eh
--    on ie.icustay_id = eh.icustay_id

-- pre-hospitalization echo weights
--left join echo_nohadm enh
--    on ie.icustay_id = enh.icustay_id
order by ie.stay_id;